apiVersion: v1
kind: Pod
metadata:
  name: job15
spec:
  containers:
  - args:
    - recurrent_network.py
    - /root/job15.csv
    - job15
    command:
    - python
    image: wzheng33/lstm
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  # nodeName: node-4.666.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
