apiVersion: v1
kind: Pod
metadata:
  name: job27
spec:
  containers:
  - args:
    - dynamic_rnn.py
    - /root/job27.csv
    - job27
    command:
    - python
    image: wzheng33/dyrnn
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  #nodeName: node-1.xiaorouji.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
