apiVersion: v1
kind: Pod
metadata:
  name: job21
spec:
  containers:
  - args:
    - recurrent_network.py
    - /root/job21.csv
    - job21
    command:
    - python
    image: wzheng33/lstm
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  #nodeName: node-3.xiaorouji.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
