apiVersion: v1
kind: Pod
metadata:
  name: job30
spec:
  containers:
  - args:
    - variational_autoencoder.py
    - /root/job30.csv
    - job30
    command:
    - python
    image: wzheng33/vae:latest
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  #nodeName: node-1.xiaorouji.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
