apiVersion: v1
kind: Pod
metadata:
  name: job6
spec:
  containers:
  - args:
    - bidirectional_rnn.py
    - /root/job6.csv
    - job6
    command:
    - python
    image: wzheng33/birnn
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  # nodeName: node-1.666.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
