apiVersion: v1
kind: Pod
metadata:
  name: job7
spec:
  containers:
  - args:
    - dynamic_rnn.py
    - /root/job7.csv
    - job7
    command:
    - python
    image: wzheng33/dyrnn
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  # nodeName: node-2.666.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
